apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-api-deployment
  namespace: default
  labels:
    app: devops-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-api
  template:
    metadata:
      labels:
        app: devops-api
    spec:
      containers:
        - name: devops-api-container
          # Docker Hub Repository와 빌드할 이미지 태그 정보
          image: jundevgo/infratest:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "384Mi"
              cpu: "1000m"
          env:
            # JVM Memory Limit Tuning for OOM Simulation
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=60.0 -XX:+UseSerialGC -XX:+PrintGCDetails"
            # ConfigMap에서 주입받는 환경변수
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: devops-config
                  key: APP_ENV
            - name: APP_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: devops-config
                  key: APP_MESSAGE
            # Downward API를 활용한 쿠버네티스 메타데이터 주입
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            # 데이터베이스 및 외부 서비스 연결 정보 추가
            - name: DB_HOST
              value: "postgres-service"
            - name: REDIS_HOST
              value: "redis-service"
            - name: KAFKA_HOST
              value: "kafka-service"
            - name: OPENSEARCH_HOST
              value: "opensearch-service"
          # Spring Boot Actuator의 Health Endpoint를 활용한 프로브 설정
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 100
            periodSeconds: 10
